cabal-version:      3.0
name:               minicheck
version:            0.1.0.0
synopsis:           CTL Model Checker written in Haskell
-- description:
homepage:           https://github.com/rascmatt/minicheck
license:            BSD-3-Clause
license-file:       LICENSE
author:             Andrey Proskurin, Matthias Raschhofer
maintainer:         e11908082@student.tuwien.ac.at
copyright:          2025 Andrey Proskurin, Matthias Raschhofer
build-type:         Simple
-- extra-source-files:

common warnings
    ghc-options: -Wall

executable minicheck
    import:           warnings
    main-is:          Main.hs
    other-modules:    Lib.Parser.Base,Lib.Parser.TS,Lib.Parser.CTL,Lib.Model.TS,
                      Lib.Model.CTL,Lib.Verify.Check,Lib.Parser.Options,
                      Lib.Extension.Minimm.Ast,Lib.Extension.Minimm.Parser,Lib.Extension.Minimm.Transform
    -- other-extensions:
    build-depends:    base ^>=4.17,
                      containers ^>=0.6.7,
                      optparse-applicative ^>=0.18,
                      monad-validate ^>=1.3,
    hs-source-dirs:   app
    default-language: Haskell2010

test-suite minicheck-test
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          Spec.hs
  other-modules:    Lib.Parser.Base,Lib.Parser.TS,Lib.Parser.CTL,Lib.Model.TS,
                    Lib.Model.CTL,Lib.Verify.Check,Lib.Parser.Options,
                    Lib.Extension.Minimm.Ast,Lib.Extension.Minimm.Parser,Lib.Extension.Minimm.Transform,
                    Parser.CTLSpec
  build-depends:    base ^>=4.17,
                    containers ^>=0.6.7,
                    hspec ^>=2.11,
  hs-source-dirs:   app, test
  default-language: Haskell2010
  build-tool-depends: hspec-discover:hspec-discover == 2.*
