cabal-version:      3.0
name:               minicheck
version:            0.1.0.0
synopsis:           CTL Model Checker written in Haskell
-- description:
homepage:           https://github.com/rascmatt/minicheck
license:            BSD-3-Clause
license-file:       LICENSE
author:             Andrey Proskurin, Matthias Raschhofer
maintainer:         e11908082@student.tuwien.ac.at
copyright:          2025 Andrey Proskurin, Matthias Raschhofer
build-type:         Simple
-- extra-source-files:

common warnings
    ghc-options: -Wall

library
  hs-source-dirs:   src
  exposed-modules:  Parser.Base,Parser.TS,Parser.CTL,Model.TS,
                    Model.CTL,Verify.Check,
                    Extension.Minimm.Ast,Extension.Minimm.Parser,Extension.Minimm.Transform
  build-depends:    base ^>=4.17,containers ^>=0.6.7
  default-language: Haskell2010

executable minicheck
    import:           warnings
    main-is:          Main.hs
    build-depends:    base ^>=4.17,
                      minicheck,
                      containers ^>=0.6.7,
                      optparse-applicative ^>=0.18,
                      monad-validate ^>=1.3,
    hs-source-dirs:   app
    default-language: Haskell2010

test-suite minicheck-test
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          Spec.hs
  other-modules:    Parser.CTLSpec,Parser.TSSpec,Extension.ParserSpec,Extension.TransformSpec
  build-depends:    base ^>=4.17,
                    minicheck,
                    containers ^>=0.6.7,
                    hspec ^>=2.11,
  hs-source-dirs:   test
  default-language: Haskell2010
  build-tool-depends: hspec-discover:hspec-discover == 2.*
