cabal-version:       2.2

name:                minicheck
version:             0.1.0.0
-- synopsis:
-- description:
homepage:            https://github.com/rascmatt/minicheck
license:             BSD-3-Clause
license-file:        LICENSE
author:              Andrey Proskurin, Matthias Raschhofer
maintainer:          matthias.raschhofer@student.tuwien.ac.at
copyright:           2025 Andrey Proskurin, Matthias Raschhofer
category:            Web
build-type:          Simple
extra-source-files:  README.md
                     CHANGELOG.md

executable minicheck
  hs-source-dirs:      src
  main-is:             Main.hs
  other-modules:       Lib.Parser.Base,Lib.Parser.TS,Lib.Parser.CTL,Lib.Model.TS,Lib.Model.CTL,Lib.Verify.Check
  default-language:    Haskell2010
  build-depends:       base >= 4.7 && < 5
  ghc-options:         -Wall
                       -Wcompat
                       -Widentities
                       -Wincomplete-record-updates
                       -Wincomplete-uni-patterns
                       -Wmissing-export-lists
                       -Wmissing-home-modules
                       -Wpartial-fields
                       -Wredundant-constraints
